### PR TITLE
Improved  basic stylings and made it mobile responsive

### PR DESCRIPTION
**Pull request by J-B-Mugundh**
Laptop View:
image

Mobile View
image

### CODE REVIEW

**Comment by J-B-Mugundh** [comment]
Laptop view:
image


Mobile view: 
image

Improved version!

**Comment by Harish-2003** [comment]
Can you reduce the header in mobile responsive?

**Comment by Harish-2003** [comment]
> @Harish-2003 
> 
> image
> 

Can u also attach screenshots of laptop view

**Comment by J-B-Mugundh** [comment]
> > @Harish-2003
> > image
> 
> Can u also attach screenshots of laptop view

Sure!

image

**Comment by J-B-Mugundh** [comment]
@Harish-2003 Could u please add gssoc-extd label to this?

**Comment by J-B-Mugundh** [comment]
@sanjay-kv @Harish-2003 @KiranBaliga @Bruhbytes Could you please add gssoc-extd label here please!

**Pull request merged**
