### PR TITLE
added crypto-slider

### PR DESCRIPTION
**Pull request by SanikaBhalerao1345**
before:
blockchainweb

after:
slider-blockchain

### CODE REVIEW

**Review by Deekshit7483 — CHANGES_REQUESTED** [review]
This branch has conflicts. Please resolve them first.

**Comment by SanikaBhalerao1345** [comment]
can you pls give level label , so I can create PR asap
thanks

**Comment by SanikaBhalerao1345** [comment]
@Deekshit7483 I have removed conflicts pls check now

**Comment by SanikaBhalerao1345** [comment]
@Harish-2003 pls check my pr and also assign the labels

**Pull request closed without merging**
