### PR TITLE
Crypto Symbol Accessibility[Issue #19]

### LINKED ISSUE #19: Adding Crypto symbols search functionality
### Project Title
blockchain[OpenTekHub]

### Problem Description:

Currently in OpenTekHub, the only search option is to search the full name of the cryptocurrency, like BITCOIN and ETHEREUM only.
I have edited the script.js file to allow Searches with the symbols too like, 
BTC --> BITCOIN
ETH --> ETHEREUM
SOL --> SOLANA

### Need for this fix

Since in the vast pool of cryptocurrencies, a frequent trader would prefer if they could check the prices with only the unique symbols instead of the complete name which coulg get repetitive and time consuming.

### Reproducing the Issue

- Visit the deployed website [here](https://opentekhub.github.io/blockchain/)
- Try Searching for the preferred Crypto using their Symbol (like BTC for BITCOIN)
- Error : "Cryptocurrency not found!"

### Error Screenshot

Screenshot 2024-09-28 235715

### Error Fix

image

### PR DESCRIPTION
**Pull request by OrganicBeetle**
### Fixes #19.
- Added Dictionary of an extensive list of commonly used Cryptocurrencies which maps the symbol to the coin.

### Error Fix

Screenshot 2024-09-28 235756

### CODE REVIEW

**Comment by Harish-2003** [comment]
Thank you for the changes I kindly request you to add the basic symbols in the place of bitcoin like
Bitcoin(BTC),ETHERUM(ETH) etc

**Comment by Harish-2003** [comment]
And remove vs code file

**Comment by OrganicBeetle** [comment]
@Harish-2003 
Thank you for the help, I have added the symbols in place to hint the users about the alternative and removed the vs code file.
Kindly review the PR and let me know about any other changes which could be needed!

**Comment by Harish-2003** [comment]
Thank you for your contribution @OrganicBeetle ✨ It's good to merge

**Review by Harish-2003 — APPROVED** [review]

**Pull request merged**
