### PR TITLE
Add Code of Conduct #1

### PR DESCRIPTION
**Pull request by KiranBaliga**
A new code of conduct.md file has been commited to the repo as per the issue description. Referenced the code of conduct template and modified it based on the project usage. Added the appropriate email ID for reporting purposes. Please review this PR and let me know your POV & review.

### CODE REVIEW

**Comment by Harish-2003** [comment]
The file name should be CODE_OF_CONDUCT.md

**Comment by Harish-2003** [comment]
Refer how the file is named https://github.com/OpenTekHub/cryptobot/blob/main/CODE_OF_CONDUCT.md

**Comment by Harish-2003** [comment]
Thank you @KiranBaliga

**Comment by KiranBaliga** [comment]
The file has been renamed as advised. Apologize for setting up a manual one. Please review.

**Comment by Harish-2003** [comment]
Thank you @KiranBaliga mention the issue

**Pull request merged**
