### PR TITLE
Added Navbar and 'About Us' & 'FAQ' sections

### PR DESCRIPTION
**Pull request by anshika-1102**
_Navbar:_ added with proper tab navigation. 

_About Us Section:_ I have integrated the content for the About Us section, featuring a video running in the background. I've ensured that the text is clearly visible and the content is properly aligned for an optimal viewing experience.

_"Why Us?" Cards:_ 4 relevant cards have been added to effectively answer the "Why Us?" question, highlighting the unique aspects of our project.

_Frequently Asked Questions:_ I have included a set of FAQs along with their answers, addressing common inquiries.

**All the media queries have been resolved.**

**Reflected changes (for desktop and mobile view):**

https://github.com/user-attachments/assets/3f7599cd-d120-4d90-9500-bd2593e1e612
https://github.com/user-attachments/assets/c03d6576-5d57-4995-86bc-e5d13fff3945

You may go through the live demo too.
https://anshika-1102.github.io/blockchain/

@Harish-2003 Please merge the repository. All tasks have been fulfilled.

### CODE REVIEW

**Comment by anshika-1102** [comment]
@Harish-2003 sir please add 'gssoc-ext' , 'hacktoberfest-accepted', 'level 2' labels to this and close the issue.

**Comment by Harish-2003** [comment]
Mention the issue

**Comment by anshika-1102** [comment]
The PR is already merged. Thank you!

**Comment by Wahid7852** [comment]
@Harish-2003 change your gssoc-extd label to gssoc-ext
otherwise no merged PRs will be reflected on the leaderboard

**Comment by Harish-2003** [comment]
Oh ok will do it

**Pull request merged**
