### PR TITLE
change the ui of the navbar

### LINKED ISSUE #100: [Bug]: Enhanced the navbar
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The current navbar design lacks certain functionalities and visual appeal that can enhance user experience and navigation. This issue aims to address these deficiencies by implementing the following changes:

### Add ScreenShots

https://github.com/user-attachments/assets/280e77c3-f245-4468-8cf8-65345f4ef5a8

### What browsers are you seeing the problem on?

_No response_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### PR DESCRIPTION
**Pull request by priyashuu**
fixes #100 
image

### CODE REVIEW

**Comment by priyashuu** [comment]
@Harish-2003  please review this please

**Comment by Harish-2003** [comment]
The navbar is disappeared

**Comment by priyashuu** [comment]
why 🥹 , lemme check it

**Comment by Harish-2003** [comment]
I am saying that the navbar contents are not visible trying adding some different colours

**Comment by priyashuu** [comment]
ok okm

**Comment by priyashuu** [comment]
image

**Comment by priyashuu** [comment]
is it okay ?

**Pull request merged**
