### PR TITLE
Improved contribution guidelines

### LINKED ISSUE #27: Add detail instruction for Contribution guidelines
I feel that the current instructions in the Contribution Guidelines are not easy to understand for contributors,
who are new to **Git** or **GitHub**. Therefore, I am planning to add more detailed but easy-to-understand _Contribution Guidelines_.

If you feel its needed and want me to work on it, 
Please assign it to me, and add required label.

### PR DESCRIPTION
**Pull request by J-B-Mugundh**
Purpose:
The previous contribution guidelines were difficult to follow, especially for new contributors. The guidelines have been improved with clearer instructions and GitHub commands to make them easier to understand and follow.

Impact:

- Simplified the contribution process by providing step-by-step instructions.
- Added GitHub commands to assist contributors in using the terminal effectively.
- Ensured clarity around key tasks such as switching branches, forking, and submitting pull requests.
- Encouraged contributors to engage with the project by starring the repository and following the organization.

Related Issue:
Resolves #27

### CODE REVIEW

**Comment by Harish-2003** [comment]
Also mention to star the repo and follow the organisation

**Comment by J-B-Mugundh** [comment]
> And why are u not writing an pr message you need to write what issue it closes and what does this pr does

I'm new to open source! I'll added them now

**Comment by Harish-2003** [comment]
Also please mention the issue in the previous pr that was merged

**Comment by Harish-2003** [comment]
And also mentioned some changes please look into it and make respective commits to the pr

**Review by Harish-2003 — APPROVED** [review]

**Comment by Harish-2003** [comment]
> And why are u not writing an pr message you need to write what issue it closes and what does this pr does

...

**Comment by J-B-Mugundh** [comment]
> And also mentioned some changes please look into it and make respective commits to the pr

I've mentioned to star the repo and follow our organization in the new commit!

**Comment by J-B-Mugundh** [comment]
> > And why are u not writing an pr message you need to write what issue it closes and what does this pr does
> 
> ...

I've edited the PR description and added in now!

**Comment by J-B-Mugundh** [comment]
Please ignore the last 2 commits. It was by mistake.

**Comment by J-B-Mugundh** [comment]
@Harish-2003 Could u please add gssoc-extd label to this?

**Comment by J-B-Mugundh** [comment]
@sanjay-kv @Harish-2003 @KiranBaliga @Bruhbytes Could you please add gssoc-extd label here please!

**Pull request merged**
