### PR TITLE
Revert "changed the complete ui of the webpage and added a static airdrop secion and contract button"

### PR DESCRIPTION
**Pull request by Harish-2003**
Reverts OpenTekHub/blockchain#47

### CODE REVIEW

**Comment by Boobeshkumar56** [comment]
I just wanted to check if my contribution has been accepted. Let me know if there's anything else you need from me.

**Comment by Harish-2003** [comment]
> I just wanted to check if my contribution has been accepted. Let me know if there's anything else you need from me.

do we have an apis for the airdrop?

**Comment by Boobeshkumar56** [comment]
yes we have but have to find a perfect one

**Comment by Boobeshkumar56** [comment]
if we dont need that let me know will update it

**Comment by Harish-2003** [comment]
i am okay with the airdrop thing ,but its better to not add until we find the correct one and i think the present ui looks good then the one you made

**Comment by Boobeshkumar56** [comment]
ok thanks let me know if anything i could do

**Comment by Harish-2003** [comment]
will look into the airdrop thing once found an perfect api for it and i have seen that you added some telegram icon to the telegram link kindly add that icon and also add the icon refercing this github repo and anything you would like to add let me know

**Comment by Boobeshkumar56** [comment]
will make a pr ASAP :)

**Pull request merged**
