### PR TITLE
Feat : Added dropdown options for crypto currencies

### PR DESCRIPTION
**Pull request by Tomkndn**
Fixes - #22 
Description - Added a dropdown menu for all the crypto currencies.
screenshot is attached below for the refernce.
image

### CODE REVIEW

**Comment by Harish-2003** [comment]
Images of implementation!

**Comment by Tomkndn** [comment]
> Images of implementation!

Are you talking about the code?

**Comment by Harish-2003** [comment]
> Fixes - #22 
> Description - Added a dropdown menu for all the crypto currencies.
> screenshot is attached below for the refernce.
> image
> 

The same implementation right?

**Comment by Harish-2003** [comment]
> > Images of implementation!
> 
> Are you talking about the code?
No about the web page

**Comment by Harish-2003** [comment]
Raise an new pr based upon the new ui/ux design

**Comment by Tomkndn** [comment]
okay there is a change in the ui/ux, so i have to update it right?

**Comment by Harish-2003** [comment]
> okay there is a change in the ui/ux, so i have to update it right?
> 

Yep

**Pull request closed without merging**
