### PR TITLE
added telegram bot link to website

### PR DESCRIPTION
**Pull request by IshuSinghSE**
This pull request includes adds link for a  to the website.

✅ https://github.com/OpenTekHub/blockchain/issues/24 Added [Telegram bot](https://t.me/trackingcryptopricerbot) link to the website
✅ https://github.com/OpenTekHub/blockchain/issues/10 Added some new Cryptocurrencies [script.js](https://github.com/OpenTekHub/blockchain/pull/26/files#diff-ed3ee7e0beea2498ff3b8ca85973d122fc6fa3d585d62b5807ec034d0cf076b3R85-R103):

#### Added the following Crptocurrencies:
image
image
image

**_I can also able to contribute to the above telegram bot at [repo](https://github.com/OpenTekHub/cryptobot)_**

Please let me know, if I have to make any changes.

### CODE REVIEW

**Comment by Harish-2003** [comment]
Can u attach the screenshot of both mobile and desktop view

**Comment by IshuSinghSE** [comment]
##  Desktop 
image

## Mobile 
image

Looking forward for your instructions...

**Comment by IshuSinghSE** [comment]
> Can u attach the screenshot of both mobile and desktop view

## Mobile
image

## Desktop
image

Looking forward for your instructions...

**Comment by Harish-2003** [comment]
The link is taking to the telegram right?

**Pull request merged**
